import { Panel,StatusBadge } from '@/components/aegis';
import { useAegis } from '@/lib/useAegis';
import { Plug,Activity,RefreshCw } from 'lucide-react';
export default function Integrations(){const {integrations,refreshIntegrations,liveNotes}=useAegis();const live=integrations.filter(i=>i.status==='LIVE').length;return <div className="p-6 space-y-6 max-w-[1200px] mx-auto"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-display font-bold tracking-tight">Integrations</h1><p className="text-sm text-muted-foreground mt-1">Real health checks for the technologies powering Vanguard</p></div><button onClick={refreshIntegrations} className="inline-flex items-center gap-2 border border-border px-3 py-2 text-xs hover:border-primary/40"><RefreshCw className="w-3.5 h-3.5"/>Refresh</button></div>
<div className="aegis-hard-panel p-4"><div className="text-xs text-muted-foreground"><span className="text-primary font-medium aegis-mono">INTEGRATION TRUTH:</span> {live} provider{live===1?' is':'s are'} currently live. Anything not configured is explicitly labeled SIMULATED, LOCAL, or DISCONNECTED.</div></div>
<div className="grid md:grid-cols-2 gap-4">{integrations.map(int=><div key={int.id} className="aegis-hard-panel p-5"><div className="flex items-start justify-between mb-3"><div className="flex items-center gap-3"><div className="w-10 h-10 border border-primary/30 bg-primary/10 flex items-center justify-center"><Plug className="w-5 h-5 text-primary"/></div><div><div className="font-display font-bold">{int.provider}</div><div className="text-xs text-muted-foreground mt-0.5">{int.features?.[0]}</div></div></div><StatusBadge status={int.status}/></div><div className="flex flex-wrap gap-1.5">{int.features?.map(f=><span key={f} className="text-[10px] px-2 py-0.5 bg-muted/20 border border-border">{f}</span>)}</div><div className="mt-4 flex items-center gap-4 text-xs text-muted-foreground"><Activity className="w-3.5 h-3.5"/><span>{int.status==='LIVE'?'Backend health check passed':'Safe fallback active'}</span></div></div>)}</div>
{liveNotes?.length>0&&<Panel title="Live Sponsor Calls" subtitle="Latest runtime activity"><div className="space-y-2">{liveNotes.map((n,i)=><div key={i} className="border border-border bg-muted/20 p-3 text-xs"><div className="flex items-center justify-between"><span className="font-bold">{n.provider}</span><StatusBadge status={n.mode}/></div><div className="text-muted-foreground mt-1 line-clamp-2">{n.text}</div></div>)}</div></Panel>}
<Panel title="Technology Roles" subtitle="Clear separation of responsibility"><div className="space-y-3"><RoleRow name="Huawei openJiuwen / WorkSwarm" role="Multi-agent collaboration layer" question="What is happening?" color="#a78bfa"/><RoleRow name="OpenAI" role="Aegis Evidence Court" question="What does the evidence support, and what is the safest response?" color="#34d399"/><RoleRow name="Aegis Gate" role="Zero-trust execution airlock" question="Are these agents actually authorized to do this?" color="#fbbf24"/><RoleRow name="Aegis Edge" role="Hardware enforcement" question="Is the signed capability valid?" color="#fb923c"/></div></Panel></div>}
function RoleRow({name,role,question,color}){return <div className="flex items-start gap-3 p-3 bg-muted/20 border border-border"><div className="w-1 h-12 shrink-0" style={{background:color}}/><div className="flex-1"><div className="font-display font-bold text-sm">{name}</div><div className="text-xs text-muted-foreground mt-0.5">{role}</div><div className="text-xs mt-1.5 italic" style={{color}}>“{question}”</div></div></div>}
