import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Shield,ArrowRight,LockKeyhole,Network,Scale,Building2,Activity,CheckCircle2,Sparkles } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import ThemeToggle from '@/components/ThemeToggle';

const miniAgents=[
  {name:'Commander',emoji:'🦅',x:'12%',y:'18%'},{name:'Security',emoji:'🦊',x:'77%',y:'18%'},{name:'Network',emoji:'🐺',x:'12%',y:'67%'},{name:'Skeptic',emoji:'🦝',x:'77%',y:'67%'},{name:'Verifier',emoji:'🐧',x:'45%',y:'43%'}
];

export default function Landing(){
  const [email,setEmail]=useState(''),[company,setCompany]=useState(''),[status,setStatus]=useState(''),[launching,setLaunching]=useState(false);
  const launch=async()=>{setLaunching(true);try{await base44.auth.demoLogin();window.location.href='/app/judge';}catch(e){setStatus(e.message);}finally{setLaunching(false);}};
  const waitlist=async e=>{e.preventDefault();setStatus('');try{await base44.api.waitlist({email,company,role:'Hack the North interest'});setStatus('You’re on the Vanguard early-access list.');setEmail('');setCompany('');}catch(e){setStatus(e.message);}};
  return <div className="min-h-screen bg-background text-foreground overflow-hidden">
    <div className="fixed inset-0 aegis-grid opacity-40 pointer-events-none"/><div className="fixed inset-0 aegis-aurora pointer-events-none"/>
    <header className="relative z-20 flex items-center justify-between max-w-7xl mx-auto px-5 md:px-8 py-5">
      <div className="flex items-center gap-3"><div className="w-10 h-10 border border-primary/60 bg-primary/10 grid place-items-center aegis-glow-cyan aegis-corner-cut"><Shield className="w-5 h-5 text-primary"/></div><div><div className="font-display font-black tracking-tight">AEGISMESH</div><div className="text-[9px] tracking-[.28em] text-muted-foreground aegis-mono">AGENT TRUST INFRASTRUCTURE</div></div></div>
      <div className="flex items-center gap-2"><ThemeToggle compact/><Link to="/login" className="hidden sm:inline-flex px-3 py-2 border border-border text-xs hover:border-primary/50 transition">Sign in</Link><button onClick={launch} disabled={launching} className="px-4 py-2 bg-primary text-primary-foreground text-xs font-bold aegis-corner-cut aegis-glow-cyan hover:brightness-110 transition">{launching?'Launching…':'Launch demo'}</button></div>
    </header>

    <main className="relative z-10">
      <section className="max-w-7xl mx-auto px-5 md:px-8 pt-16 md:pt-24 pb-20 grid lg:grid-cols-[1.05fr_.95fr] gap-14 items-center">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1.5 border border-primary/30 bg-primary/5 text-primary text-[10px] aegis-mono tracking-widest mb-7"><Sparkles className="w-3 h-3"/> HACK THE NORTH 2026 · B2B AGENT CONTROL PLANE</div>
          <h1 className="font-display font-black text-5xl md:text-7xl leading-[.95] tracking-[-.045em] max-w-4xl">AI can be wrong.<br/><span className="aegis-text-cyan">Authority shouldn’t be.</span></h1>
          <p className="mt-7 text-lg text-muted-foreground max-w-2xl leading-relaxed">Vanguard lets enterprise AI agents investigate together, challenge each other, and propose real actions—while a zero-trust control plane prevents one poisoned, hallucinating, or unauthorized agent from touching production.</p>
          <div className="mt-8 flex flex-wrap gap-3"><button onClick={launch} className="inline-flex items-center gap-2 px-5 py-3 bg-primary text-primary-foreground font-bold text-sm aegis-corner-cut aegis-glow-cyan">Enter 90-second judge demo <ArrowRight className="w-4 h-4"/></button><a href="#architecture" className="inline-flex items-center gap-2 px-5 py-3 border border-border bg-card/50 text-sm hover:border-primary/40">See how it works</a></div>
          <div className="mt-10 grid grid-cols-3 max-w-xl border-y border-border/80 divide-x divide-border/80"><Stat n="7" label="specialist agents"/><Stat n="2-key" label="high-risk control"/><Stat n="0" label="unrestricted agents"/></div>
        </div>

        <div className="relative min-h-[480px] aegis-hard-panel p-5 md:p-7">
          <div className="flex items-center justify-between pb-4 border-b border-border"><div><div className="text-xs font-bold tracking-widest aegis-mono">LIVE SWARM PREVIEW</div><div className="text-[10px] text-muted-foreground mt-1">Agents can disagree. Policy still wins.</div></div><div className="flex items-center gap-2 text-[10px] text-green-400 aegis-mono"><span className="w-2 h-2 bg-green-400 animate-pulse"/> SYSTEM HEALTHY</div></div>
          <div className="relative h-[360px] mt-5 overflow-hidden border border-border/70 bg-background/45 aegis-grid">
            <svg className="absolute inset-0 w-full h-full opacity-50" preserveAspectRatio="none"><line x1="20%" y1="25%" x2="50%" y2="50%" stroke="hsl(var(--primary))" strokeWidth="1" strokeDasharray="7 7" className="animate-aegis-dash"/><line x1="80%" y1="25%" x2="50%" y2="50%" stroke="hsl(var(--primary))" strokeWidth="1" strokeDasharray="7 7" className="animate-aegis-dash"/><line x1="20%" y1="75%" x2="50%" y2="50%" stroke="hsl(var(--primary))" strokeWidth="1" strokeDasharray="7 7" className="animate-aegis-dash"/><line x1="80%" y1="75%" x2="50%" y2="50%" stroke="hsl(var(--destructive))" strokeWidth="1" strokeDasharray="7 7" className="animate-aegis-dash"/></svg>
            {miniAgents.map((a,i)=><div key={a.name} className="absolute -translate-x-1/2 -translate-y-1/2" style={{left:a.x,top:a.y,animation:`aegis-float ${3+i*.35}s ease-in-out infinite`}}><div className={`w-20 h-20 grid place-items-center border bg-card/90 text-3xl aegis-corner-cut ${a.name==='Verifier'?'border-green-400/50 aegis-glow-green':'border-primary/30'}`}>{a.emoji}</div><div className="text-[9px] text-center mt-2 aegis-mono text-muted-foreground">{a.name}</div></div>)}
            <div className="absolute left-1/2 bottom-4 -translate-x-1/2 text-center"><div className="px-3 py-2 border border-red-500/40 bg-red-500/10 text-red-300 text-[10px] aegis-mono aegis-corner-cut">UNAUTHORIZED ACTION → BLOCKED</div></div>
          </div>
        </div>
      </section>

      <section id="architecture" className="border-y border-border bg-card/30"><div className="max-w-7xl mx-auto px-5 md:px-8 py-16"><div className="max-w-2xl"><div className="text-[10px] aegis-mono tracking-[.2em] text-primary">THREE QUESTIONS. THREE LAYERS.</div><h2 className="text-3xl md:text-4xl font-black tracking-tight mt-3">Built so intelligence never equals authority.</h2></div><div className="grid md:grid-cols-3 gap-4 mt-10"><Layer icon={Network} title="Huawei openJiuwen" q="What is happening?" body="Specialist agents decompose incidents, investigate in parallel, challenge hypotheses, use tools, and reassign work if one agent fails."/><Layer icon={Scale} title="OpenAI Evidence Court" q="What does the evidence support?" body="Independent adjudication weighs conflicting evidence, runs counterfactuals, and proposes the least-destructive safe response."/><Layer icon={LockKeyhole} title="Aegis Gate" q="Are we allowed to act?" body="Policy, identity, trust, human approval, and one-time signed execution capabilities stand between AI intent and production."/></div></div></section>

      <section className="max-w-7xl mx-auto px-5 md:px-8 py-20 grid lg:grid-cols-2 gap-10"><div><div className="text-[10px] aegis-mono tracking-[.2em] text-primary">WHY ENTERPRISES PAY</div><h2 className="text-3xl md:text-4xl font-black mt-3">Move agents from read-only to governed action.</h2><p className="text-muted-foreground mt-5 leading-relaxed">The economic problem isn’t access to smarter models. It’s whether a bank, telecom, utility, hospital, or cloud operator can safely give those models production authority. Vanguard reduces the blast radius of mistakes while accelerating incident investigation and containment.</p><div className="grid sm:grid-cols-2 gap-3 mt-7"><Value icon={Activity} title="Faster containment" text="Parallel agents investigate while humans focus on high-impact decisions."/><Value icon={Shield} title="Fewer unsafe actions" text="Least privilege and policy blocks remain in force even if an agent is fooled."/><Value icon={Building2} title="Enterprise adoption" text="Governed execution unlocks higher-value workflows than read-only copilots."/><Value icon={CheckCircle2} title="Auditable control" text="Evidence, approvals, policy decisions, and execution are replayable end to end."/></div></div>
        <form onSubmit={waitlist} className="aegis-hard-panel p-7 self-start"><div className="text-[10px] aegis-mono tracking-[.2em] text-primary">EARLY ACCESS</div><h3 className="text-2xl font-black mt-2">Join the Vanguard waitlist</h3><p className="text-sm text-muted-foreground mt-2">For teams deploying agents into security, infrastructure, cloud, and critical operations.</p><label className="block text-xs mt-6 mb-2">Work email</label><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" className="w-full bg-background/60 border border-border px-3 py-3 outline-none focus:border-primary/60"/><label className="block text-xs mt-4 mb-2">Company / team</label><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Optional" className="w-full bg-background/60 border border-border px-3 py-3 outline-none focus:border-primary/60"/><button className="w-full mt-5 bg-primary text-primary-foreground font-bold py-3 aegis-corner-cut">Request early access</button>{status&&<div className="mt-3 border border-primary/20 bg-primary/5 p-3 text-xs text-primary flex items-center justify-between gap-3"><span>{status}</span>{status.startsWith('You’re')&&<button type="button" onClick={launch} className="shrink-0 underline underline-offset-4 hover:text-foreground">Explore demo →</button>}</div>}</form>
      </section>
    </main>
    <footer className="relative z-10 border-t border-border px-5 md:px-8 py-6 text-center text-[10px] text-muted-foreground aegis-mono">AEGISMESH · INVESTIGATE · CHALLENGE · CONTROL</footer>
  </div>;
}
function Stat({n,label}){return <div className="py-4 px-3 first:pl-0"><div className="font-black text-xl text-foreground">{n}</div><div className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</div></div>}
function Layer({icon:Icon,title,q,body}){return <div className="aegis-hard-panel p-5"><div className="w-9 h-9 grid place-items-center border border-primary/30 bg-primary/10"><Icon className="w-4 h-4 text-primary"/></div><div className="font-bold mt-5">{title}</div><div className="text-primary text-sm mt-2">“{q}”</div><p className="text-xs leading-relaxed text-muted-foreground mt-3">{body}</p></div>}
function Value({icon:Icon,title,text}){return <div className="border border-border bg-card/30 p-4"><Icon className="w-4 h-4 text-primary"/><div className="font-bold text-sm mt-3">{title}</div><p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">{text}</p></div>}
