import { Link,Outlet,useLocation } from 'react-router-dom';
import { Shield,Activity,Users,Scale,ShieldCheck,FileCheck,Server,BookOpen,Trophy,LogOut,ExternalLink } from 'lucide-react';
import { useAegis } from '@/lib/useAegis';
import { useAuth } from '@/lib/AuthContext';
import ThemeToggle from '@/components/ThemeToggle';
const NAV=[{section:'PRESENT'},{to:'/app',label:'Overview',icon:Activity},{to:'/app/judge',label:'Judge Mode',icon:Trophy},{section:'INVESTIGATE'},{to:'/app/incidents/INC-2026-0919-001',label:'War Room',icon:Shield},{to:'/app/evidence-court',label:'Evidence Court',icon:Scale},{section:'CONTROL'},{to:'/app/aegis-gate',label:'Aegis Gate',icon:ShieldCheck},{to:'/app/approvals',label:'Approvals',icon:FileCheck},{section:'FLEET & INFRASTRUCTURE'},{to:'/app/agents',label:'Agent Fleet',icon:Users},{to:'/app/infrastructure',label:'Infrastructure',icon:Server},{to:'/app/resources',label:'Resources',icon:BookOpen}];
export default function Layout(){const {demoMode,metrics,incidents,agents}=useAegis();const {logout}=useAuth();const loc=useLocation();const activeIncidents=incidents.filter(i=>i.state!=='CONTAINED'&&i.state!=='RESOLVED').length;const quarantined=agents.filter(a=>a.status==='QUARANTINED').length;return <div className="min-h-screen flex bg-background text-foreground">
<aside className="w-60 shrink-0 border-r border-border bg-sidebar/70 backdrop-blur-xl flex flex-col relative overflow-hidden"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary/60 to-transparent"/><div className="px-5 py-5 border-b border-border"><Link to="/app" className="flex items-center gap-2.5 group"><div className="relative w-9 h-9 bg-primary/10 border border-primary/40 flex items-center justify-center aegis-glow-cyan aegis-corner-cut"><Shield className="w-5 h-5 text-primary"/><div className="absolute inset-0 border border-primary/20 animate-aegis-pulse-ring"/></div><div><div className="font-display font-black text-[15px] tracking-tight leading-none">Vanguard</div><div className="text-[9px] text-muted-foreground mt-1 aegis-mono tracking-[.14em]">INVESTIGATE · CHALLENGE · CONTROL</div></div></Link></div>
<nav className="flex-1 overflow-y-auto px-2 py-3 space-y-0.5">{NAV.map((item,i)=>item.section?<div key={i} className="px-3 pt-4 pb-1 text-[9px] aegis-mono uppercase tracking-[.18em] text-muted-foreground/55">{item.section}</div>:(()=>{const {to,label,icon:Icon}=item;const active=to==='/app'?loc.pathname==='/app':loc.pathname.startsWith(to);return <Link key={to} to={to} className={`group relative flex items-center gap-2.5 px-3 py-2 text-[13px] transition-all border ${active?'bg-primary/10 text-primary border-primary/30 shadow-[inset_3px_0_0_hsl(var(--primary))]':'text-muted-foreground hover:text-foreground hover:bg-muted/40 border-transparent hover:border-border'}`}><Icon className="w-4 h-4 shrink-0"/><span className="truncate">{label}</span>{label==='War Room'&&activeIncidents>0&&<span className="ml-auto text-[10px] px-1.5 py-0.5 bg-destructive/20 text-red-400 aegis-mono">{activeIncidents}</span>}{label==='Agent Fleet'&&quarantined>0&&<span className="ml-auto text-[10px] px-1.5 py-0.5 bg-destructive/20 text-red-400 aegis-mono">{quarantined}</span>}</Link>})())}</nav>
<div className="px-3 py-3 border-t border-border space-y-2"><div className="flex items-center justify-between text-[10px] aegis-mono"><span className="text-muted-foreground">MODE</span><span className={`px-1.5 py-0.5 ${demoMode?'bg-amber-500/15 text-amber-400':'bg-green-500/15 text-green-400'}`}>{demoMode?'DEMO SIMULATION':'LIVE'}</span></div><div className="grid grid-cols-2 gap-1.5 text-[10px] aegis-mono"><div className="px-2 py-1.5 bg-muted/30 border border-border"><div className="text-muted-foreground">BLOCKED</div><div className="text-red-400 font-bold">{metrics.unsafe_blocked}</div></div><div className="px-2 py-1.5 bg-muted/30 border border-border"><div className="text-muted-foreground">QUARANTINED</div><div className="text-red-400 font-bold">{metrics.quarantined_agents}</div></div></div><div className="flex gap-1.5"><ThemeToggle compact/><Link to="/" className="flex-1 inline-flex items-center justify-center border border-border text-muted-foreground hover:text-foreground" title="Landing page"><ExternalLink className="w-3.5 h-3.5"/></Link><button onClick={()=>logout(true)} className="flex-1 inline-flex items-center justify-center border border-border text-muted-foreground hover:text-red-400" title="Log out"><LogOut className="w-3.5 h-3.5"/></button></div></div>
</aside><main className="flex-1 overflow-y-auto aegis-grid relative"><div className="fixed top-0 left-60 right-0 h-[2px] bg-gradient-to-r from-transparent via-primary/60 to-transparent opacity-40 pointer-events-none animate-aegis-scan"/><Outlet/></main></div>}
