import { URL } from 'node:url';
import { loadState, mutate, entityCollection, newId } from './store.mjs';
import { ensureDemoUser, issueToken, requireUser, hashPassword, checkPassword } from './auth.mjs';
import { evaluateAuthorization, RISK_LEVELS, POLICIES } from './policy.mjs';
import { issueCapability } from './capability.mjs';
import { openAIVerify, jiuwenDispatch, integrationStatus } from './integrations.mjs';

const json=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));};
const bad=(res,status,msg)=>json(res,status,{error:msg});
const readBody=req=>{ if(req.body!==undefined&&req.body!==null){ if(typeof req.body==='object') return Promise.resolve(req.body); if(typeof req.body==='string'&&req.body.trim()){ try{return Promise.resolve(JSON.parse(req.body));}catch{return Promise.reject(Object.assign(new Error('Invalid JSON'),{status:400}));} } } return new Promise((resolve,reject)=>{let b='';let settled=false;req.on('data',d=>{if(settled)return;b+=d;if(b.length>2_000_000){settled=true;reject(Object.assign(new Error('Payload too large'),{status:413}));}});req.on('end',()=>{if(settled)return;if(!b)return resolve({});try{resolve(JSON.parse(b));}catch{reject(Object.assign(new Error('Invalid JSON'),{status:400}));}});req.on('error',reject);}); };
const userSafe=u=>{if(!u)return null;const {passwordHash,salt,otp,...safe}=u;return safe;};
const sortRecords=(records,sort)=>{if(!sort)return records;let desc=false,key=sort;if(sort.startsWith('-')){desc=true;key=sort.slice(1);}return [...records].sort((a,b)=>{const av=a[key]??'',bv=b[key]??'';return (av>bv?1:av<bv?-1:0)*(desc?-1:1);});};
const matches=(r,q)=>Object.entries(q||{}).every(([k,v])=>Array.isArray(v)?Array.isArray(r[k])&&v.every(x=>r[k].includes(x)):r[k]===v);

async function authRoutes(req,res,path){
  if(path==='/api/auth/demo'&&req.method==='POST'){const u=await ensureDemoUser();return json(res,200,{access_token:issueToken(u),user:userSafe(u)});}
  if(path==='/api/auth/login'&&req.method==='POST'){const b=await readBody(req);const st=await loadState();const u=st.users.find(x=>x.email===String(b.email||'').toLowerCase());if(!u||!u.verified||!checkPassword(String(b.password||''),u))return bad(res,401,'Invalid email or password');return json(res,200,{access_token:issueToken(u),user:userSafe(u)});}
  if(path==='/api/auth/me'&&req.method==='GET'){return json(res,200,userSafe(await requireUser(req)));}
  if(path==='/api/auth/register'&&req.method==='POST'){const b=await readBody(req);const email=String(b.email||'').trim().toLowerCase();const password=String(b.password||'');if(!email.includes('@')||password.length<8)return bad(res,400,'Use a valid email and password of at least 8 characters');const out=await mutate(st=>{if(st.users.some(x=>x.email===email))throw Object.assign(new Error('Account already exists'),{status:409});const {salt,hash}=hashPassword(password);const otp=String(Math.floor(100000+Math.random()*900000));const u={id:newId('usr'),email,role:'user',verified:false,salt,passwordHash:hash,otp,otpExpires:Date.now()+10*60*1000,created_at:new Date().toISOString()};st.users.push(u);return {email,dev_otp:process.env.NODE_ENV==='production'?undefined:otp};});return json(res,201,out);}
  if(path==='/api/auth/verify-otp'&&req.method==='POST'){const b=await readBody(req);const email=String(b.email||'').toLowerCase();const out=await mutate(st=>{const u=st.users.find(x=>x.email===email);if(!u||u.otp!==String(b.otpCode||'')||u.otpExpires<Date.now())throw Object.assign(new Error('Invalid or expired verification code'),{status:400});u.verified=true;delete u.otp;delete u.otpExpires;if(!st.entities.User.find(x=>x.id===u.id))st.entities.User.push({id:u.id,email:u.email,role:u.role,created_date:u.created_at});return {access_token:issueToken(u),user:userSafe(u)};});return json(res,200,out);}
  if(path==='/api/auth/resend-otp'&&req.method==='POST'){const b=await readBody(req);const email=String(b.email||'').toLowerCase();const out=await mutate(st=>{const u=st.users.find(x=>x.email===email);if(!u)return {};u.otp=String(Math.floor(100000+Math.random()*900000));u.otpExpires=Date.now()+10*60*1000;return {dev_otp:process.env.NODE_ENV==='production'?undefined:u.otp};});return json(res,200,out);}
  if(path==='/api/auth/forgot'&&req.method==='POST'){const b=await readBody(req);const result=await mutate(st=>{const u=st.users.find(x=>x.email===String(b.email||'').toLowerCase());if(!u)return {token:null};const token=newId('reset');st.resetTokens.push({token,userId:u.id,expires:Date.now()+30*60*1000});return {token};});return json(res,200,{ok:true,dev_reset_token:process.env.NODE_ENV==='production'?undefined:result.token});}
  if(path==='/api/auth/reset'&&req.method==='POST'){const b=await readBody(req);await mutate(st=>{const rt=st.resetTokens.find(x=>x.token===b.resetToken&&x.expires>Date.now());if(!rt)throw Object.assign(new Error('Invalid or expired reset token'),{status:400});const u=st.users.find(x=>x.id===rt.userId);const {salt,hash}=hashPassword(String(b.newPassword||''));u.salt=salt;u.passwordHash=hash;st.resetTokens=st.resetTokens.filter(x=>x!==rt);return null;});return json(res,200,{ok:true});}
  return false;
}

async function entityRoutes(req,res,path,url){
  const m=path.match(/^\/api\/entities\/([^/]+)(?:\/([^/]+))?$/); if(!m)return false;
  await requireUser(req);const name=decodeURIComponent(m[1]),id=m[2]&&decodeURIComponent(m[2]);
  if(req.method==='GET'&&!id){const st=await loadState();let records=entityCollection(st,name);const filter=url.searchParams.get('filter');if(filter){try{records=records.filter(r=>matches(r,JSON.parse(filter)));}catch{}}records=sortRecords(records,url.searchParams.get('sort'));const limit=Number(url.searchParams.get('limit')||500);return json(res,200,records.slice(0,limit));}
  if(req.method==='POST'&&!id){const b=await readBody(req);const rec=await mutate(st=>{const arr=entityCollection(st,name);const r={id:newId(name.toLowerCase()),...b,created_date:new Date().toISOString(),updated_date:new Date().toISOString()};arr.push(r);return r;});return json(res,201,rec);}
  if(req.method==='PATCH'&&id){const b=await readBody(req);const rec=await mutate(st=>{const arr=entityCollection(st,name);const r=arr.find(x=>x.id===id);if(!r)throw Object.assign(new Error('Record not found'),{status:404});Object.assign(r,b,{updated_date:new Date().toISOString()});return r;});return json(res,200,rec);}
  if(req.method==='DELETE'&&id){await mutate(st=>{const arr=entityCollection(st,name);const i=arr.findIndex(x=>x.id===id);if(i<0)throw Object.assign(new Error('Record not found'),{status:404});arr.splice(i,1);});return json(res,200,{ok:true});}
  return bad(res,405,'Method not allowed');
}

async function authorizeAction(req,user,b){
  let remoteVerdict=null;
  if(process.env.CLOUDFLARE_GATE_URL){try{const r=await fetch(`${process.env.CLOUDFLARE_GATE_URL.replace(/\/$/,'')}/authorize`,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.CLOUDFLARE_GATE_TOKEN?{Authorization:`Bearer ${process.env.CLOUDFLARE_GATE_TOKEN}`}:{})},body:JSON.stringify(b)});if(r.ok)remoteVerdict=await r.json();}catch(e){console.warn('Cloudflare gate unavailable; local policy fallback:',e.message);}}
  return mutate(st=>{const agent=st.entities.GovernedAgent.find(x=>x.agent_key===b.agent_key);const verdict=remoteVerdict||evaluateAuthorization(agent,{action:b.action,risk:b.risk||'MEDIUM',verifierConfidence:b.verifier_confidence,humanRequired:b.human_required});let rec=st.entities.ActionRequest.find(x=>x.request_id===b.request_id);const fields={request_id:b.request_id,incident_id:b.incident_id,agent_key:b.agent_key,action:b.action,target:b.target,risk:RISK_LEVELS.includes(b.risk)?b.risk:'MEDIUM',blast_radius:b.blast_radius,reversible:b.reversible===true,required_permission:b.required_permission,verifier_confidence:Number(b.verifier_confidence)||0,human_required:b.human_required===true,status:verdict.status,reason:verdict.reason,checks:verdict.checks,simulated:!process.env.JIUWEN_A2A_URL,updated_date:new Date().toISOString()};if(rec)Object.assign(rec,fields);else{rec={id:newId('action'),...fields,created_date:new Date().toISOString()};st.entities.ActionRequest.push(rec);}st.entities.AuditEvent.push({id:newId('audit'),incident_id:b.incident_id,actor_type:'agent',actor_id:b.agent_key,event:'action.requested',decision:verdict.status==='BLOCKED'?'DENY':verdict.status==='APPROVAL_REQUIRED'?'PENDING':'AUTO_APPROVED',reason:verdict.reason,source:'LIVE',created_date:new Date().toISOString()});let quarantined=false;if(verdict.status==='BLOCKED'&&['HIGH','CRITICAL'].includes(fields.risk)&&agent){const newTrust=Math.max(0,(agent.trust_score||100)-65);quarantined=newTrust<50;agent.trust_score=newTrust;agent.violations=(agent.violations||0)+1;agent.quarantined=quarantined;agent.status=quarantined?'QUARANTINED':agent.status;agent.trust_history=[...(agent.trust_history||[]),{date:new Date().toISOString(),trust:newTrust,reason:`Unauthorized request: ${b.action}`}].slice(-50);}return {status:verdict.status,reason:verdict.reason,checks:verdict.checks,action_request_id:rec.id,quarantined};});
}

async function recordApproval(req,user,b){
  return mutate(st=>{const ar=st.entities.ActionRequest.find(x=>x.request_id===b.request_id);if(!ar)throw Object.assign(new Error(`Action request ${b.request_id} not found`),{status:404});const decision=['APPROVED','REJECTED'].includes(b.decision)?b.decision:null;if(!decision)throw Object.assign(new Error('decision must be APPROVED or REJECTED'),{status:400});ar.status=decision;ar.reason=`Human ${decision.toLowerCase()} via ${b.method||'MANUAL'} by ${user.email}`;const approval={id:newId('approval'),action_request_id:b.request_id,incident_id:ar.incident_id,approver_email:user.email,method:b.method||'MANUAL',nfc_badge_id:b.nfc_badge_id||null,decision,simulated:false,created_date:new Date().toISOString()};let capability=null;if(decision==='APPROVED'){capability=issueCapability({actionRequest:ar,approval});Object.assign(approval,{capability_id:capability.capability_id,capability_nonce:capability.nonce,capability_expires_at:capability.expires_at,capability_status:'ISSUED',capability_signature:capability.signature});}else approval.capability_status='NA';st.entities.Approval.push(approval);st.entities.AuditEvent.push({id:newId('audit'),incident_id:ar.incident_id,actor_type:'human',actor_id:user.email,event:'approval.received',decision,reason:ar.reason,source:'LIVE',created_date:new Date().toISOString()});return {decision,approval_id:approval.id,capability,action_request_id:ar.id};});
}

async function recordInvestigationEvent(req,user,b){
  return mutate(st=>{const d=b.data||{},type=b.type;const findInc=id=>st.entities.Incident.find(x=>x.incident_id===id);if(type==='incident.created'){let inc=findInc(d.id);const f={incident_id:d.id,title:d.title||'Untitled incident',severity:d.severity||'MEDIUM',state:d.state||'DETECTED',affected_assets:d.affected_assets||[],simulated:false};if(inc)Object.assign(inc,f);else st.entities.Incident.push({id:newId('incident'),...f,created_date:new Date().toISOString()});}else if(type==='incident.state_changed'||type==='incident.contained'){const inc=findInc(d.id);if(inc){inc.state=type==='incident.contained'?'CONTAINED':d.state;if(inc.state==='CONTAINED')inc.contained_at=new Date().toISOString();}}else if(type==='hypothesis.updated'){const inc=findInc(d.incident_id);if(inc&&Number(d.confidence)>=Number(inc.confidence||0)){inc.leading_hypothesis=d.title;inc.confidence=Number(d.confidence)||0;}}else if(type==='verifier.verdict'){const inc=findInc(d.incident_id);if(inc)Object.assign(inc,{verdict:d.verdict,confidence:Number(d.confidence)||inc.confidence,verdict_reason:d.reason,recommended_action:d.recommended});}else if(type==='evidence.created'){st.entities.Evidence.push({id:newId('evidence'),incident_id:d.incident_id,agent_id:d.agent_id,title:d.title||'Evidence item',type:d.type,source:d.source,reliability:Number(d.reliability)||null,confidence:Number(d.confidence)||null,supports:d.supports,contradicts:d.contradicts,simulated:false,created_date:new Date().toISOString()});}else if(type==='agent.quarantined'){const a=st.entities.GovernedAgent.find(x=>x.agent_key===d.agent_id);if(a){a.status='QUARANTINED';a.quarantined=true;a.trust_score=Number(d.trust)||a.trust_score;}}st.entities.AuditEvent.push({id:newId('audit'),incident_id:d.incident_id||d.id||null,actor_type:'system',actor_id:'aegis-runtime',event:type,decision:'RECORDED',reason:d.reason||d.title||'',source:'LIVE',created_date:new Date().toISOString()});return {ok:true,type};});
}

async function functionRoutes(req,res,path){const m=path.match(/^\/api\/functions\/([^/]+)$/);if(!m)return false;const user=await requireUser(req);const b=await readBody(req);let out;if(m[1]==='authorizeAction')out=await authorizeAction(req,user,b);else if(m[1]==='recordApproval')out=await recordApproval(req,user,b);else if(m[1]==='recordInvestigationEvent')out=await recordInvestigationEvent(req,user,b);else if(m[1]==='escalatePendingApprovals')out=await mutate(st=>{let count=0;for(const ar of st.entities.ActionRequest.filter(x=>x.status==='APPROVAL_REQUIRED'&&!x.escalated)){ar.escalated=true;count++;}return {ok:true,escalated:count};});else return bad(res,404,'Unknown function');return json(res,200,out);}

export async function handleApi(req,res){
  try{
    res.setHeader('Cache-Control','no-store');
    if(req.method==='OPTIONS'){res.statusCode=204;return res.end();}
    const url=new URL(req.url,'http://localhost');const path=url.pathname;
    if(path==='/api/health')return json(res,200,{ok:true,name:'Vanguard API',time:new Date().toISOString(),integrations:integrationStatus()});
    if(path==='/api/public-settings')return json(res,200,{id:'vanguard',public_settings:{auth_required:true,google_oauth_enabled:false,demo_enabled:true}});
    if(path==='/api/waitlist'&&req.method==='POST'){const b=await readBody(req);const email=String(b.email||'').trim().toLowerCase();if(!email.includes('@'))return bad(res,400,'Enter a valid email');const rec=await mutate(st=>{let r=st.waitlist.find(x=>x.email===email);if(!r){r={id:newId('wait'),email,company:String(b.company||'').slice(0,120),role:String(b.role||'').slice(0,120),created_at:new Date().toISOString()};st.waitlist.push(r);}return r;});return json(res,201,{ok:true,id:rec.id});}
    const a=await authRoutes(req,res,path);if(a!==false)return a;
    const e=await entityRoutes(req,res,path,url);if(e!==false)return e;
    const f=await functionRoutes(req,res,path);if(f!==false)return f;
    if(path==='/api/integrations/status'&&req.method==='GET'){await requireUser(req);return json(res,200,integrationStatus());}
    if(path==='/api/ai/verify'&&req.method==='POST'){await requireUser(req);return json(res,200,await openAIVerify(await readBody(req)));}
    if(path==='/api/jiuwen/dispatch'&&req.method==='POST'){await requireUser(req);return json(res,200,await jiuwenDispatch(await readBody(req)));}
    if(path==='/api/edge/status'&&req.method==='GET'){await requireUser(req);if(!process.env.EDGE_DEVICE_URL)return json(res,200,{mode:'SIMULATED',ok:true,service:'Aegis Edge',gpio:false,relay:'SIMULATED',message:'No EDGE_DEVICE_URL configured; safe hardware simulation is active.'});try{const r=await fetch(`${process.env.EDGE_DEVICE_URL.replace(/\/$/,'')}/status`,{headers:{...(process.env.EDGE_DEVICE_TOKEN?{'X-Aegis-Token':process.env.EDGE_DEVICE_TOKEN}:{})}});const text=await r.text();if(!r.ok)return bad(res,502,`Edge status unavailable: ${text.slice(0,300)}`);let data;try{data=JSON.parse(text)}catch{data={result:text}}return json(res,200,{mode:'LIVE',...data});}catch(e){return json(res,200,{mode:'ERROR',ok:false,message:e.message});}}
    if(path==='/api/edge/test'&&req.method==='POST'){await requireUser(req);const body=await readBody(req);const test=String(body.test||'').toUpperCase();if(!['LED','BUZZER','NFC','RELAY'].includes(test))return bad(res,400,'Unsupported edge test');if(!process.env.EDGE_DEVICE_URL)return json(res,200,{mode:'SIMULATED',ok:true,test,result:`${test} test simulated safely`});try{const r=await fetch(`${process.env.EDGE_DEVICE_URL.replace(/\/$/,'')}/test`,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.EDGE_DEVICE_TOKEN?{'X-Aegis-Token':process.env.EDGE_DEVICE_TOKEN}:{})},body:JSON.stringify({test})});const text=await r.text();if(!r.ok)return bad(res,502,`Edge test rejected: ${text.slice(0,300)}`);let data;try{data=JSON.parse(text)}catch{data={result:text}}return json(res,200,{mode:'LIVE',...data});}catch(e){return json(res,200,{mode:'ERROR',ok:false,test,message:e.message});}}
    if(path==='/api/edge/execute'&&req.method==='POST'){await requireUser(req);const body=await readBody(req);if(!process.env.EDGE_DEVICE_URL)return json(res,200,{mode:'SIMULATED',result:'No EDGE_DEVICE_URL configured; hardware action simulated safely.'});const r=await fetch(`${process.env.EDGE_DEVICE_URL.replace(/\/$/,'')}/execute`,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.EDGE_DEVICE_TOKEN?{'X-Aegis-Token':process.env.EDGE_DEVICE_TOKEN}:{})},body:JSON.stringify(body)});const text=await r.text();if(!r.ok)return bad(res,502,`Edge device rejected command: ${text.slice(0,300)}`);let data;try{data=JSON.parse(text)}catch{data={result:text}}return json(res,200,{mode:'LIVE',...data});}
    if(path==='/api/policies'&&req.method==='GET'){await requireUser(req);return json(res,200,POLICIES);}
    return bad(res,404,'API route not found');
  }catch(err){console.error(err);return bad(res,err.status||500,err.message||'Internal error');}
}
